# Generated by Django 5.1.15 on 2026-09-08 23:37

import app.core.managers
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Professor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "core_professor",
            },
            managers=[
                ("objects", app.core.managers.ProfessorManager()),
            ],
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "options_per_question",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(2),
                            django.core.validators.MaxValueValidator(6),
                        ]
                    ),
                ),
                (
                    "marking_mode",
                    models.CharField(
                        choices=[
                            ("partial", "Partial"),
                            ("all_or_nothing", "All Or Nothing"),
                        ],
                        default="partial",
                        max_length=16,
                    ),
                ),
                ("negative_marking", models.BooleanField(default=False)),
                ("default_points", models.FloatField(default=1.0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("versioned", "Versioned"),
                            ("printed", "Printed"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "professor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quizzes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "quizzes",
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_index", models.PositiveIntegerField()),
                ("text", models.TextField()),
                ("options", models.JSONField()),
                ("correct_options", models.JSONField()),
                ("points", models.FloatField(blank=True, null=True)),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="core.quiz",
                    ),
                ),
            ],
            options={
                "ordering": ["order_index"],
            },
        ),
        migrations.CreateModel(
            name="RosterEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=200)),
                (
                    "external_id",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roster_entries",
                        to="core.quiz",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "roster entries",
            },
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("needs_review", "Needs Review"),
                            ("finalized", "Finalized"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "failure_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("qr_unreadable", "Qr Unreadable"),
                            ("alignment_failed", "Alignment Failed"),
                        ],
                        default="",
                        max_length=32,
                    ),
                ),
                (
                    "student_label",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("total_score", models.FloatField(blank=True, null=True)),
                ("raw_image_path", models.CharField(max_length=500)),
                (
                    "rectified_image_path",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "answer_hash",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("photo", "Photo"), ("batch_pdf", "Batch Pdf")],
                        max_length=16,
                    ),
                ),
                ("batch_id", models.UUIDField(blank=True, null=True)),
                ("page_number", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "duplicate_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="duplicates",
                        to="core.submission",
                    ),
                ),
                (
                    "roster_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submissions",
                        to="core.rosterentry",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("scored", "Scored"),
                            ("overridden", "Overridden"),
                            ("assigned", "Assigned"),
                            ("rescored", "Rescored"),
                            ("duplicate_confirmed", "Duplicate Confirmed"),
                            ("suggested", "Suggested"),
                            ("printed", "Printed"),
                        ],
                        max_length=40,
                    ),
                ),
                ("detail", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor_professor",
                    models.ForeignKey(
                        blank=True,
                        help_text="null = system action",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_events",
                        to="core.quiz",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_events",
                        to="core.submission",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_no", models.PositiveIntegerField()),
                ("detected_options", models.JSONField()),
                ("confidence", models.FloatField()),
                ("flagged", models.BooleanField(default=False)),
                (
                    "flag_reason",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("correct", models.BooleanField(blank=True, null=True)),
                ("score", models.FloatField(blank=True, null=True)),
                ("manually_edited", models.BooleanField(default=False)),
                ("edited_at", models.DateTimeField(blank=True, null=True)),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="core.submission",
                    ),
                ),
            ],
            options={
                "ordering": ["question_no"],
            },
        ),
        migrations.CreateModel(
            name="Version",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_number", models.PositiveIntegerField()),
                (
                    "qr_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("question_order", models.JSONField()),
                ("option_order", models.JSONField()),
                ("template_version", models.PositiveIntegerField()),
                ("printed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="core.quiz",
                    ),
                ),
            ],
            options={
                "ordering": ["version_number"],
            },
        ),
        migrations.AddField(
            model_name="submission",
            name="version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="submissions",
                to="core.version",
            ),
        ),
        migrations.AddConstraint(
            model_name="quiz",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("options_per_question__gte", 2), ("options_per_question__lte", 6)
                ),
                name="quiz_options_per_question_2_to_6",
            ),
        ),
        migrations.AddConstraint(
            model_name="quiz",
            constraint=models.CheckConstraint(
                condition=models.Q(("default_points__gte", 0)),
                name="quiz_default_points_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="question",
            constraint=models.UniqueConstraint(
                fields=("quiz", "order_index"), name="question_unique_order"
            ),
        ),
        migrations.AddConstraint(
            model_name="answer",
            constraint=models.UniqueConstraint(
                fields=("submission", "question_no"), name="answer_unique_question"
            ),
        ),
        migrations.AddConstraint(
            model_name="version",
            constraint=models.UniqueConstraint(
                fields=("quiz", "version_number"), name="version_unique_number"
            ),
        ),
    ]
