# Generated by Django 5.1.15 on 2026-09-09 12:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_immutability_triggers"),
    ]

    operations = [
        migrations.AddField(
            model_name="version",
            name="anticluster_fallback",
            field=models.BooleanField(default=False),
        ),
    ]
